[package]
name = "faropdf"
version = "0.1.1"
description = "FaroPDF desktop application"
authors = ["maoscripts"]
edition = "2021"

[lib]
name = "faropdf_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
lopdf = { version = "0.33", default-features = false, features = ["pom_parser"] }
tauri-plugin-updater = "2.10.1"
keyring = "3"
