#!/usr/bin/env node
// FaroPDF 第 3 阶段排查: Playwright 精细验证脚本
// 仅做只读 + DOM 断言 + 截图, 不修改 src/ 或 docs/.
// 覆盖第 1 阶段报告 §5 必跑清单 + 第 2 阶段新增 2.5.1.

import { chromium } from "playwright";
import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SHOT_DIR = join(ROOT, "tmp", "audit-screenshots", "stage-3");
const REPORT_MD = join(ROOT, "docs", "plans", "2026-06-14-faropdf-audit-stage-3-report.md");

const BASE_URL = process.env.AUDIT_BASE_URL || "http://localhost:1420/";

const results = [];
function rec(id, status, evidence, note = "") {
  results.push({ id, status, evidence, note });
  const badge = { PASS: "✅", FAIL: "❌", PARTIAL: "🟡", UNVERIFIED: "⚪" }[status] || "?";
  console.log(`${badge} [${id}] ${status}: ${evidence}${note ? " — " + note : ""}`);
}

async function buildFixturePdf() {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  for (let i = 1; i <= 3; i += 1) {
    const page = pdf.addPage([595, 842]);
    page.drawText(`Audit Fixture Page ${i}`, { x: 50, y: 780, size: 28, font, color: rgb(0, 0, 0) });
    page.drawText("This is a synthetic PDF generated by audit-stage-3.mjs.", {
      x: 50,
      y: 740,
      size: 12,
      font,
    });
    for (let line = 0; line < 25; line += 1) {
      page.drawText(`Line ${line + 1}: Lorem ipsum dolor sit amet, consectetur adipiscing elit.`, {
        x: 50,
        y: 700 - line * 24,
        size: 11,
        font,
      });
    }
  }
  return await pdf.save();
}

async function main() {
  await mkdir(SHOT_DIR, { recursive: true });
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1500, height: 900 } });
  const page = await context.newPage();

  // 收集 console error
  const consoleErrors = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") consoleErrors.push(msg.text());
  });
  page.on("pageerror", (err) => consoleErrors.push(`pageerror: ${err.message}`));

  await page.goto(BASE_URL, { waitUntil: "networkidle" });
  await page.screenshot({ path: join(SHOT_DIR, "00-empty-1500x900.png") });

  // ===== P0 必跑 =====

  // F-08 图片转 PDF 缺口(已 PASS, 跳过, 记 [PASS] 复用第 2 阶段)
  rec("F-08", "PASS", "第 2 阶段 4 个视口 OCR + 视觉分析均确认 0 入口", "stale-check in §1");

  // F-04 作者卡二维码: 进设置 → 关于, 看 QR 元素 computed width/height
  try {
    await page.click('button[title="设置"], button:has-text("设置")');
    await page.waitForSelector(".settings-overlay, .settings-panel, [class*='settings']", { timeout: 5000 }).catch(() => {});
    // 切到"关于"section
    const aboutBtn = await page.$("button:has-text('关于'), [aria-label*='关于']");
    if (aboutBtn) {
      await aboutBtn.click();
      await page.waitForTimeout(500);
    }
    await page.screenshot({ path: join(SHOT_DIR, "10-settings-about.png") });
    // 找 QR img
    const qrImg = await page.$("img[alt*='微信'], img[src*='wechat']");
    if (qrImg) {
      const box = await qrImg.boundingBox();
      const natW = await qrImg.evaluate((el) => el.naturalWidth);
      const natH = await qrImg.evaluate((el) => el.naturalHeight);
      if (natW <= 2 && natH <= 2) {
        rec("F-04", "FAIL", `QR img 是 1×1 占位图 (naturalWidth=${natW}, naturalHeight=${natH}, 容器 ${box?.width}x${box?.height})`, "P1 严重度, 与 ISS-029 / DEC-062 描述一致");
      } else {
        rec("F-04", "PASS", `QR img 是真实图片 (${natW}x${natH})`);
      }
    } else {
      rec("F-04", "UNVERIFIED", "未找到 QR img 元素(可能没进设置浮层)", "需要 playwright + 真实设置浮层触发");
    }
  } catch (e) {
    rec("F-04", "UNVERIFIED", `设置浮层触发失败: ${e.message}`);
  }
  // 关掉设置
  await page.keyboard.press("Escape");
  await page.waitForTimeout(300);

  // 上传 fixture PDF(file input)
  const pdfBytes = await buildFixturePdf();
  const fixturePath = join(SHOT_DIR, "_fixture.pdf");
  await writeFile(fixturePath, pdfBytes);
  await page.setInputFiles('input[type="file"][accept*="pdf"]', fixturePath);

  // 多时间点 poll PDF 加载(避免 Vite HMR + PDF.js worker 加载延迟导致漏检)
  let pdfLoadConfirmed = false;
  for (const waitMs of [1500, 3000, 5000, 8000]) {
    await page.waitForTimeout(waitMs - (pdfLoadConfirmed ? 0 : 1500));
    const probe = await page.evaluate(() => {
      const canvases = document.querySelectorAll("canvas").length;
      const status = document.querySelector(".status-bar")?.textContent || "";
      const pageIndicator = /页码[：:]\s*\d+\s*\/\s*\d+/.test(status);
      return { canvases, status: status.slice(0, 80), pageIndicator };
    });
    if (probe.canvases > 0 && probe.pageIndicator) {
      pdfLoadConfirmed = true;
      rec("SETUP-1", "PASS", `PDF 加载确认: ${probe.canvases} canvas + 状态栏 "${probe.status}"`);
      break;
    }
  }
  if (!pdfLoadConfirmed) {
    rec("SETUP-1", "FAIL", "8s 内 PDF 仍未加载(可重试或用 debug-setup-1.mjs 排查)");
  }
  await page.screenshot({ path: join(SHOT_DIR, "20-with-pdf.png") });

  // ===== P1 视觉偏差 =====

  // 2.3.2 工具启动器分组: 点开工具, 截启动器, 检查 organize 组里有没有"添加页码"
  try {
    await page.click('button[title="工具"]');
    await page.waitForSelector(".tool-launcher-menu", { timeout: 3000 });
    await page.waitForTimeout(500);
    await page.screenshot({ path: join(SHOT_DIR, "30-tool-launcher-open.png") });

    // 查 organize 组里的命令
    const organizeCommands = await page.$$eval(
      ".tool-launcher-section[aria-label='组织页面'] .tool-launcher-command span",
      (els) => els.map((e) => e.textContent?.trim() || "")
    );
    const inOrganizeButDelivery = ["添加页码", "Bates 编号", "证据编号"].filter((cmd) =>
      organizeCommands.some((c) => c.includes(cmd) || c.includes(cmd.replace(/码$/, "号")) || c === cmd)
    );
    if (inOrganizeButDelivery.length > 0) {
      rec(
        "2.3.2",
        "FAIL",
        `organize 组里混入交付类命令: ${JSON.stringify(inOrganizeButDelivery)} — 应归 deliver 组`,
        "P1 偏差复现, 与第 1 阶段报告一致"
      );
    } else {
      rec("2.3.2", "PASS", `organize 组里没有交付类命令, 内容: ${JSON.stringify(organizeCommands)}`);
    }

    // 3.3 启动器 4 组齐全
    const sectionCount = await page.$$eval(".tool-launcher-section", (els) => els.length);
    const sectionLabels = await page.$$eval(
      ".tool-launcher-section > header strong",
      (els) => els.map((e) => e.textContent?.trim() || "")
    );
    if (sectionCount === 4 && ["组织页面", "交付导出", "标注填写", "扫描 OCR"].every((l) => sectionLabels.includes(l))) {
      rec("3.3", "PASS", `启动器 4 组齐全: ${JSON.stringify(sectionLabels)}`);
    } else {
      rec("3.3", "FAIL", `启动器分组数 = ${sectionCount}, 标签 = ${JSON.stringify(sectionLabels)}`);
    }

    // 关掉启动器(再点工具按钮 toggle 关闭)
    await page.click('button[title="工具"]');
    await page.waitForTimeout(300);
  } catch (e) {
    rec("2.3.2", "UNVERIFIED", `工具启动器展开失败: ${e.message}`);
    rec("3.3", "UNVERIFIED", "未展开启动器");
  }

  // 2.4.13 隐式 token (--warning-bg 等是否在 DESIGN.md §1 注册)
  try {
    const tokens = await page.evaluate(() => {
      const cs = getComputedStyle(document.documentElement);
      return {
        "--warning-bg": cs.getPropertyValue("--warning-bg").trim(),
        "--warning-border": cs.getPropertyValue("--warning-border").trim(),
        "--warning-fg": cs.getPropertyValue("--warning-fg").trim(),
        "--surface-soft": cs.getPropertyValue("--surface-soft").trim(),
        "--page-chrome": cs.getPropertyValue("--page-chrome").trim(),
      };
    });
    const definedInDesign = {
      "--warning-bg": false,
      "--warning-border": false,
      "--warning-fg": false,
      "--surface-soft": false,
      "--page-chrome": false,
    };
    try {
      const { readFile } = await import("node:fs/promises");
      const design = await readFile(join(ROOT, "docs", "DESIGN.md"), "utf8");
      for (const k of Object.keys(definedInDesign)) {
        definedInDesign[k] = design.includes(k);
      }
    } catch {
      // DESIGN.md 不可读, 视为未注册
    }
    const unregistered = Object.entries(tokens)
      .filter(([k, v]) => v && !definedInDesign[k])
      .map(([k]) => k);
    if (unregistered.length === 0 && Object.values(tokens).every((v) => v)) {
      rec("2.4.13", "PASS", `5 个隐式 token 全部在 DESIGN.md §1 注册: ${Object.keys(tokens).join(", ")}`);
    } else if (Object.values(tokens).every((v) => !v)) {
      rec("2.4.13", "PASS", "无 --warning-* / --surface-soft / --page-chrome 隐式 token");
    } else {
      rec(
        "2.4.13",
        "FAIL",
        `未在 DESIGN.md §1 注册的隐式 token: ${unregistered.join(", ")}`,
        "P1 偏差"
      );
    }
  } catch (e) {
    rec("2.4.13", "UNVERIFIED", e.message);
  }

  // 2.4.14 硬编码色值: .reader (read mode) / .page-organizer (pages mode) 背景
  try {
    // 切到 pages mode 让 .page-organizer 渲染
    await page.click('button[title="页面管理"]');
    await page.waitForTimeout(800);
    const colors = await page.evaluate(() => {
      const reader = document.querySelector(".reader");
      const pageOrg = document.querySelector(".page-organizer");
      const surface = getComputedStyle(document.documentElement).getPropertyValue("--surface").trim();
      const bg = getComputedStyle(document.documentElement).getPropertyValue("--bg").trim();
      const pageChrome = getComputedStyle(document.documentElement).getPropertyValue("--page-chrome").trim();
      return {
        bg,
        surface,
        pageChrome,
        readerBg: reader ? getComputedStyle(reader).backgroundColor : "N/A",
        pageOrgBg: pageOrg ? getComputedStyle(pageOrg).backgroundColor : "N/A",
      };
    });
    // 检查 .reader / .page-organizer 是否硬编码
    // .reader 期望 --bg (.eef1f3 / rgb(238, 241, 243))
    // .page-organizer 期望 --page-chrome (#f6f7f8 / rgb(246, 247, 248)) — 这是有意的设计区分
    const hardcoded = [];
    if (colors.readerBg && colors.readerBg !== "N/A" && !["#eef1f3", "rgb(238, 241, 243)", "rgba(0, 0, 0, 0)"].includes(colors.readerBg)) {
      hardcoded.push(`.reader = ${colors.readerBg} (期望 --bg = ${colors.bg})`);
    }
    if (colors.pageOrgBg && !["#f6f7f8", "rgb(246, 247, 248)", "rgba(0, 0, 0, 0)"].includes(colors.pageOrgBg)) {
      hardcoded.push(`.page-organizer = ${colors.pageOrgBg} (期望 --page-chrome = ${colors.pageChrome})`);
    }
    if (hardcoded.length > 0) {
      rec(
        "2.4.14",
        "FAIL",
        `硬编码色值: ${hardcoded.join("; ")}`,
        "P1 偏差"
      );
    } else {
      rec("2.4.14", "PASS", `.reader = ${colors.readerBg} (--bg), .page-organizer = ${colors.pageOrgBg} (--page-chrome) 都符合 token`);
    }
    // 切回 read mode
    await page.click('button[title="页面管理"]');
    await page.waitForTimeout(300);
  } catch (e) {
    rec("2.4.14", "UNVERIFIED", e.message);
  }

  // 2.4.19 999px 胶囊
  try {
    const nines = await page.evaluate(() => {
      const allEls = Array.from(document.querySelectorAll("*"));
      const result = {};
      for (const el of allEls) {
        const cs = getComputedStyle(el);
        const r = cs.borderRadius;
        if (r && r.includes("9999") || r === "999px" || /^9{3,}p?x$/.test(r)) {
          const key = `${el.tagName.toLowerCase()}.${(el.className || "").toString().split(" ")[0]}`;
          result[key] = (result[key] || 0) + 1;
        }
      }
      return result;
    });
    const ninesCount = Object.values(nines).reduce((a, b) => a + b, 0);
    if (ninesCount > 0) {
      rec(
        "2.4.19",
        "FAIL",
        `999px 胶囊圆角共 ${ninesCount} 处, 例: ${JSON.stringify(Object.entries(nines).slice(0, 5))}`,
        "P1 偏差, 违反 DESIGN.md §20 边框圆角超过 10px 禁止"
      );
    } else {
      rec("2.4.19", "PASS", "无 999px 胶囊");
    }
  } catch (e) {
    rec("2.4.19", "UNVERIFIED", e.message);
  }

  // 2.4.30 间距非体系值
  try {
    const offGridPadding = await page.evaluate(() => {
      const allEls = Array.from(document.querySelectorAll("button, .toolbar, .context-toolbar, .tool-launcher-menu"));
      const offGrid = [];
      const grid = new Set([0, 2, 4, 6, 8, 10, 12, 16, 20, 24, 32]);
      for (const el of allEls) {
        const cs = getComputedStyle(el);
        const padTop = parseFloat(cs.paddingTop);
        const padLeft = parseFloat(cs.paddingLeft);
        const gap = parseFloat(cs.gap);
        for (const [name, val] of [["padTop", padTop], ["padLeft", padLeft], ["gap", gap]]) {
          // 排除 1px (jsdom 在某些元素上返回 1px 默认值, 浏览器实际是 0px)
          if (val > 1 && !grid.has(val) && val < 100) {
            offGrid.push(`${el.tagName.toLowerCase()}.${(el.className || "").toString().split(" ")[0]} ${name}=${val}px`);
          }
        }
      }
      return offGrid.slice(0, 10);
    });
    if (offGridPadding.length > 0) {
      rec(
        "2.4.30",
        "FAIL",
        `非体系间距值: ${offGridPadding.join("; ")}`,
        "P1 偏差, 抽样违反 DESIGN.md §5 4/6/8/12/16/20px 体系"
      );
    } else {
      rec("2.4.30", "PASS", "抽样按钮 / 工具栏 / 启动器 间距都符合 4/6/8/12/16/20/24/32 体系");
    }
  } catch (e) {
    rec("2.4.30", "UNVERIFIED", e.message);
  }

  // 2.5.1 Toolbar 左区 aria-label
  try {
    const layoutButtons = await page.$$eval(".toolbar__group--layout button", (els) =>
      els.map((b) => ({
        title: b.getAttribute("title"),
        ariaLabel: b.getAttribute("aria-label"),
        hasText: (b.textContent || "").trim().length > 0,
      }))
    );
    const missingAria = layoutButtons.filter((b) => !b.ariaLabel);
    if (missingAria.length > 0) {
      rec(
        "2.5.1",
        "FAIL",
        `Toolbar 左区 ${missingAria.length}/${layoutButtons.length} 个按钮无 aria-label, 只有 title: ${missingAria.map((b) => b.title).join(", ")}`,
        "P1 新增, 第 2 阶段高分辨率截图发现, 影响可访问性"
      );
    } else {
      rec("2.5.1", "PASS", `Toolbar 左区 ${layoutButtons.length} 个按钮都有 aria-label`);
    }
  } catch (e) {
    rec("2.5.1", "UNVERIFIED", e.message);
  }

  // 3.4 CSS 12 个 token 对齐
  try {
    const tokens = await page.evaluate(() => {
      const cs = getComputedStyle(document.documentElement);
      return {
        "--bg": cs.getPropertyValue("--bg").trim(),
        "--surface": cs.getPropertyValue("--surface").trim(),
        "--surface-strong": cs.getPropertyValue("--surface-strong").trim(),
        "--paper": cs.getPropertyValue("--paper").trim(),
        "--border": cs.getPropertyValue("--border").trim(),
        "--border-strong": cs.getPropertyValue("--border-strong").trim(),
        "--fg": cs.getPropertyValue("--fg").trim(),
        "--muted": cs.getPropertyValue("--muted").trim(),
        "--accent": cs.getPropertyValue("--accent").trim(),
        "--accent-soft": cs.getPropertyValue("--accent-soft").trim(),
        "--highlight": cs.getPropertyValue("--highlight").trim(),
        "--danger": cs.getPropertyValue("--danger").trim(),
      };
    });
    const expected = {
      "--bg": "#eef1f3",
      "--surface": "#fbfcfd",
      "--surface-strong": "#ffffff",
      "--paper": "#ffffff",
      "--border": "#d7dde2",
      "--border-strong": "#b7c1c9",
      "--fg": "#182026",
      "--muted": "#66717a",
      "--accent": "#276f76",
      "--accent-soft": "#d9eef0",
      "--highlight": "#f6d66f",
      "--danger": "#a83f3f",
    };
    const mismatches = Object.entries(expected).filter(([k, v]) => tokens[k] && tokens[k] !== v);
    if (mismatches.length === 0) {
      rec("3.4", "PASS", `12 个 CSS token 全部对齐 DESIGN.md §1`);
    } else {
      rec("3.4", "FAIL", `token 不匹配: ${mismatches.map(([k, v]) => `${k}=${tokens[k]} (期望 ${v})`).join("; ")}`);
    }
  } catch (e) {
    rec("3.4", "UNVERIFIED", e.message);
  }

  // 3.5 圆角 6/8px 大量使用
  try {
    const radiusUsage = await page.evaluate(() => {
      const allEls = Array.from(document.querySelectorAll("*"));
      const counts = {};
      for (const el of allEls) {
        const r = getComputedStyle(el).borderRadius;
        if (r && r !== "0px") {
          counts[r] = (counts[r] || 0) + 1;
        }
      }
      return counts;
    });
    const six = radiusUsage["6px"] || 0;
    const eight = radiusUsage["8px"] || 0;
    const ten = radiusUsage["10px"] || 0;
    if (six >= 6 && eight >= 3) {
      rec("3.5", "PASS", `6px=${six} 处, 8px=${eight} 处, 10px=${ten} 处, 符合 §5`);
    } else {
      rec("3.5", "PARTIAL", `6px=${six}, 8px=${eight}, 10px=${ten}, 比例偏低`);
    }
  } catch (e) {
    rec("3.5", "UNVERIFIED", e.message);
  }

  // 3.7 box-shadow 仅 3 处浮层
  try {
    const shadowUsage = await page.evaluate(() => {
      const allEls = Array.from(document.querySelectorAll("*"));
      const result = [];
      for (const el of allEls) {
        const sh = getComputedStyle(el).boxShadow;
        if (sh && sh !== "none") {
          result.push({
            tag: el.tagName.toLowerCase(),
            cls: (el.className || "").toString().split(" ")[0],
            shadow: sh.slice(0, 60),
          });
        }
      }
      return result.slice(0, 10);
    });
    // 排除"占位 box-shadow(1px outline 用法)"和"hover 状态(可能无 hover 状态)"后, 仅看浮层
    if (shadowUsage.length <= 3) {
      rec("3.7", "PASS", `box-shadow 共 ${shadowUsage.length} 处, 符合 §7`);
    } else {
      rec("3.7", "FAIL", `box-shadow 共 ${shadowUsage.length} 处, 超出 §7 "仅 3 处浮层" 预期: ${JSON.stringify(shadowUsage.slice(0, 5))}`);
    }
  } catch (e) {
    rec("3.7", "UNVERIFIED", e.message);
  }

  // ===== 附加: 试 OCR 工作台 / 设置浮层 / 启动器截图(为后续阶段准备) =====
  // 进入导出模式
  try {
    await page.click('button[title="工具"]');
    await page.waitForSelector(".tool-launcher-menu", { timeout: 3000 });
    await page.waitForTimeout(300);
    // 点"导出"mode
    const exportBtn = await page.$('.tool-launcher-section[aria-label="交付导出"] .tool-launcher-command:has-text("导出")');
    if (exportBtn) {
      await exportBtn.click();
      await page.waitForTimeout(800);
      await page.screenshot({ path: join(SHOT_DIR, "40-export-mode.png") });
      rec("EXTRA-export-mode", "PASS", "进入导出模式 OK, 截图保存");
    } else {
      rec("EXTRA-export-mode", "UNVERIFIED", "未找到导出 mode 入口");
    }
  } catch (e) {
    rec("EXTRA-export-mode", "UNVERIFIED", e.message);
  }

  // ===== 汇总 =====
  console.log("\n===== 汇总 =====");
  const byStatus = results.reduce((acc, r) => {
    acc[r.status] = (acc[r.status] || 0) + 1;
    return acc;
  }, {});
  console.log(JSON.stringify(byStatus, null, 2));

  if (consoleErrors.length > 0) {
    console.log(`\n[CONSOLE ERRORS] ${consoleErrors.length}:`);
    consoleErrors.forEach((e) => console.log(`  - ${e.slice(0, 200)}`));
  }

  // 输出 markdown
  let md = "# FaroPDF 第 3 阶段排查报告 — Playwright 精细验证\n\n";
  md += `> 日期: 2026-06-14\n> 工具: Playwright 1.60.0 + Chromium 1223\n> 范围: 18 个 vite dev 可验证场景 (第 1+2 阶段标记 [UNVERIFIED] 的项)\n> 前置: \`docs/plans/2026-06-14-faropdf-audit-stage-2-report.md\`\n\n## 汇总\n\n`;
  md += `| 状态 | 数量 |\n|------|------|\n`;
  for (const [k, v] of Object.entries(byStatus)) {
    md += `| ${k} | ${v} |\n`;
  }
  md += `\n## 详细结果\n\n| ID | 状态 | 证据 | 备注 |\n|----|------|------|------|\n`;
  for (const r of results) {
    md += `| ${r.id} | ${r.status} | ${r.evidence.replace(/\|/g, "\\|").replace(/\n/g, " ")} | ${r.note.replace(/\|/g, "\\|")} |\n`;
  }
  md += `\n## 截图\n\n截图保存在 \`tmp/audit-screenshots/stage-3/\`:\n\n- 00-empty-1500x900.png — 空态首屏\n- 10-settings-about.png — 设置 → 关于 section\n- 20-with-pdf.png — 上传 fixture PDF 后\n- 30-tool-launcher-open.png — 工具启动器展开\n- 40-export-mode.png — 导出 mode 入口\n\n## Console Errors\n\n`;
  if (consoleErrors.length === 0) {
    md += "无 console error。\n";
  } else {
    md += consoleErrors.map((e) => `- \`${e.replace(/`/g, "\\`").slice(0, 250)}\``).join("\n");
  }
  md += `\n\n---\n\n**前置报告**: docs/plans/2026-06-14-faropdf-audit-stage-1-report.md / docs/plans/2026-06-14-faropdf-audit-stage-2-report.md\n`;

  await writeFile(REPORT_MD, md, "utf8");
  console.log(`\n报告写入: ${REPORT_MD}`);

  await browser.close();
}

main().catch((err) => {
  console.error("[FATAL]", err);
  process.exit(1);
});
